# paths.yaml

##########################################################################################

# PATHS
data_state_paths:
  raw: data/raw/uber.csv
  sdo: data/sdo/uber.parquet
  process1: data/sdo/initial_process.parquet
  features1: data/sdo/initial_features.parquet
  features2: data/sdo/model_features.parquet
  interim: data/interim/
  result: data/result_frames/dynamic-prices.parquet

##########################################################################################

##########################################################################################
