# paths.yaml

##########################################################################################

# PATHS
data_state_paths:
  raw: data/raw/uber.csv
  sdo: data/sdo/uber.parquet
  process1: data/sdo/initial_process.parquet
  features1: data/sdo/initial_features.parquet
  bound_features: data/sdo/bound_features.parquet
  interim: data/interim/
  frame_result2: data/result_frames/
  frame_result1: data/result_frames/sma.parquet
  result1: reports/results/bound_hours.json


  temp: data/temp/

##########################################################################################

##########################################################################################
